- ormconfig.json.sample
- package.json
- src/logion/migration/1636720219315-InitialSchema.ts
* Rename constraints in order to have same names across all DB instances.
* Fix config that prevent backend to start while referencing typescript migrations.
> DB Migrations: Polish

- resources/schemas.json
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/controllers/protectionrequest.controller.ts
- src/logion/migration/1666083444245-AddCompany.ts
- src/logion/migration/1666182071461-AddCompany.ts
- src/logion/model/locrequest.model.ts
- src/logion/model/personalinfo.model.ts
- src/logion/model/useridentity.ts
- src/logion/services/seal.service.ts
- test/integration/model/locrequest.model.spec.ts
- test/unit/controllers/locrequest.controller.spec.ts
- test/unit/controllers/protectionrequest.controller.spec.ts
- test/unit/controllers/vaulttransferrequest.controller.spec.ts
- test/unit/model/locrequest.model.spec.ts
- test/unit/model/protectionrequest.model.spec.ts
- test/unit/services/notification-test-data.ts
- test/unit/services/seal.service.spec.ts
* Company flag (true = I represent a company) was turned into a name (defined = I represent a company with given legal entity name)
* That information was moved from user identity to LOC request (only taken into account with Identity LOCs)
* As the initial migration has not been applied yet in DEV, it was modified to fit with the new model
> Change company flag into name

- src/logion/model/locrequest.model.ts
- test/integration/model/locrequest.model.spec.ts
* Eager loading is disabled when using a query builder
* In that case, relations to load have to be explicitly configured with a join
* Not doing so implies empty files, metadata and links fields in returned views on fetch with specification
> Load LOC request relations on find by spec

- src/logion/model/locrequest.model.ts
- test/integration/model/loc_requests_order.sql
- test/integration/model/locrequest.model.spec.ts
A global order by clause is setup, so that LOC requests will appear following this order:
1. REQUESTED LOCs, ordered by descending created_on,
1. REJECTED LOC requests, ordered by descending created_on,
1. OPEN LOCs, ordered by descending loc_created_on,
1. CLOSED LOCs, ordered by descending closed_on,
1. VOIDED LOCs, ordered by descending voided_on.
logion-network/logion-internal#639
> Fine-tune order by clause to fetch loc requests.

- src/logion/lib/ipfs/FileManager.ts
This PR *temporarily* disables the removal of file from IPFS.
Commented-out code (aka "Dead code") is left on purpose.
logion-network/logion-internal#645
> feat: disable IPFS removal.

- src/logion/container/app.container.ts
- src/logion/services/ownershipcheck.service.ts
- src/logion/services/singular.service.ts
- test/unit/services/ownershipcheck.service.spec.ts
* Ownership check is now possible with Singular Kusama NFTs (but not yet Statemine)
* The check uses Singular's REST API
logion-network/logion-internal#650
> Add singular_kusama ownership check

- resources/schemas.json
- src/logion/app.support.ts
- src/logion/app.ts
- src/logion/controllers/collection.controller.ts
- src/logion/controllers/components.ts
- src/logion/controllers/fileupload.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/controllers/lofile.controller.ts
- test/unit/app.spec.ts
- test/unit/controllers/collection.controller.spec.ts
- test/unit/controllers/locrequest.controller.spec.ts
- test/unit/controllers/lofile.controller.spec.ts
* Backend now expects a client-side generated hash and compares it with its own
* File hash is not returned anymore by the backend (if the request passes, client has the guarantee that provided hash is shared with the server)
logion-network/logion-internal#665
> Check file hash on upload

- src/logion/services/singular.service.ts
Singular web service provides nft owner's addresses in Kusama format (prefix 2), while our frontend/backend only deal with Substrate format (42), so retrieved need to be converted.
logion-network/logion-internal#650
> chore: convert singular nft owner's addresses to Substrate (42).

- resources/schemas.json
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/model/locrequest.model.ts
- test/unit/model/locrequest.model.spec.ts
- test/unit/services/notification-test-data.ts
* A single resource was added enabling the setting of the flag
* `verifiedThirdParty` flag was added to the LOC request view
logion-network/logion-internal#678
> Add API for VTP flag

- package.json
- src/logion/container/app.container.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/controllers/verifiedthirdparty.controller.ts
- src/logion/model/locrequest.model.ts
- src/logion/services/locrequest.service.ts
- src/logion/services/locsynchronization.service.ts
- test/integration/model/locrequest.model.spec.ts
- test/unit/controllers/locrequest.controller.shared.ts
- test/unit/services/locsynchronization.service.spec.ts
- yarn.lock
* Using `@DefaultTransactional` decorator introduced [here](https://github.com/logion-network/logion-rest-api-core/commit/0fbe7d31ce1f75f201b174e6d9060a90287c3c21); data source is configured to use a transactional context; `DefaultTransactional` uses serializable default isolation level.
* `LocRequestService` is the facade implementing transaction bounds.
logion-network/logion-internal#644
> Transactional LOC request updates

- package.json
- src/logion/container/app.container.ts
- src/logion/controllers/lofile.controller.ts
- src/logion/controllers/protectionrequest.controller.ts
- src/logion/controllers/setting.controller.ts
- src/logion/controllers/vaulttransferrequest.controller.ts
- src/logion/controllers/verifiedthirdparty.controller.ts
- src/logion/model/syncpoint.model.ts
- src/logion/model/verifiedthirdpartyselection.model.ts
- src/logion/services/blockconsumption.service.ts
- src/logion/services/lofile.service.ts
- src/logion/services/protectionrequest.service.ts
- src/logion/services/protectionsynchronization.service.ts
- src/logion/services/settings.service.ts
- src/logion/services/syncpoint.service.ts
- src/logion/services/transaction.service.ts
- src/logion/services/transactionsync.service.ts
- src/logion/services/vaulttransferrequest.service.ts
- src/logion/services/verifiedthirdpartyselection.service.ts
- test/unit/controllers/locrequest.controller.shared.ts
- test/unit/controllers/lofile.controller.spec.ts
- test/unit/controllers/protectionrequest.controller.spec.ts
- test/unit/controllers/setting.controller.spec.ts
- test/unit/controllers/vaulttransferrequest.controller.spec.ts
- test/unit/services/blockconsumption.service.spec.ts
- test/unit/services/protectionsynchronization.service.spec.ts
- test/unit/services/transactionsync.service.spec.ts
- yarn.lock
* Adds missing services and use them in controllers and/or sync services
* Logged queries (not enabled by default, set `TYPEORM_LOGGING` to true in `Dockerfile` to test) show that transactions are indeed started and committed for all updates
logion-network/logion-internal#644
> Enable transactions for all updates

- resources/schemas.json
- src/logion/controllers/adapters/verifiedthirdpartyadapter.ts
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/controllers/verifiedthirdparty.controller.ts
- src/logion/migration/1669287321053-AddSelectedFlag.ts
- src/logion/model/verifiedthirdpartyselection.model.ts
- src/logion/services/verifiedthirdpartyselection.service.ts
- test/integration/model/verifiedthirdpartyselection.model.spec.ts
- test/unit/controllers/locrequest.controller.fetch.spec.ts
- test/unit/controllers/locrequest.controller.items.spec.ts
- test/unit/controllers/locrequest.controller.shared.ts
- test/unit/controllers/locrequest.controller.sof.spec.ts
- test/unit/controllers/verifiedthirdparty.controller.spec.ts
- test/unit/model/verifiedthirdpartyselection.model.spec.ts
* VerifiedThirdPartySelections are not deleted anymore on unselection
* A flag now tells if the VerifiedThirdPartySelection is "active" or not
* Access rules have been updated accordingly
logion-network/logion-internal#676
> Keep unselected parties in LOC

- src/logion/model/verifiedthirdpartyselection.model.ts
- src/logion/services/locsynchronization.service.ts
- test/unit/model/verifiedthirdpartyselection.model.spec.ts
* Link sync was broken following refactoring
* Prevent that requester is also selected as VTP on its own LOC (which makes no sense)
> Fix link sync and VTP selection

- package.json
- src/logion/controllers/fileupload.ts
- test/unit/controllers/fileupload.spec.ts
- yarn.lock
* Upgraded express dependencies via rest-api-core (not strictly necessary for the fix)
* Properly decode file names (latin1 encoded by default)
logion-network/logion-internal#697
> fix: file name encoding on upload.

- package.json
- src/logion/lib/ipfs/FileManager.ts
- yarn.lock
* Downloading large files from IPFS was causing a memory leak because data were downloaded faster than being written to disk.
* Implementing an explicit "back pressure" mechanism solves the issue.
logion-network/logion-internal#736
> Enable large file download

- resources/schemas.json
- src/logion/controllers/adapters/locrequestadapter.ts
- src/logion/controllers/collection.controller.ts
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/migration/1674830602953-AddLocFileSize.ts
- src/logion/model/locrequest.model.ts
- src/logion/services/idenfy/idenfy.service.ts
- test/integration/model/loc_requests.sql
- test/integration/model/locrequest.model.spec.ts
- test/unit/controllers/collection.controller.spec.ts
- test/unit/controllers/locrequest.controller.fetch.spec.ts
- test/unit/controllers/locrequest.controller.items.spec.ts
- test/unit/model/locrequest.model.spec.ts
* Provide new endpoint to serve all deliveries of all files of a given collection: `/api/collection/${collectionId}/file-deliveries`.
* Add new attribute to LOC files: `size`.
* Rename item GET endpoint from `/:collectionLocId/:itemId` to `/:collectionLocId/items/:itemId` to avoid "catch-all" effect.
logion-network/logion-internal#743
logion-network/logion-internal#750
> Improve deliveries

- resources/schemas.json
- src/logion/controllers/collection.controller.ts
- src/logion/controllers/components.ts
- test/unit/controllers/collection.controller.spec.ts
* Add `originalFileHash` to resource checking one single collection file delivery
* Fixes incomplete doc.
logion-network/logion-internal#758
logion-network/logion-internal#738
> Add originalFileHash to resource checking one single collection file delivery

- src/logion/controllers/collection.controller.ts
- test/unit/controllers/collection.controller.spec.ts
Add resource to check item ownership regardless of any file context.
logion-network/logion-internal#767
> Add resource to check item ownership.

- resources/schemas.json
- src/logion/app.support.ts
- src/logion/container/app.container.ts
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/controllers/records.controller.ts
- src/logion/migration/1676475638637-TokensRecord.ts
- src/logion/model/tokensrecord.model.ts
- src/logion/services/locauthorization.service.ts
- src/logion/services/locsynchronization.service.ts
- src/logion/services/tokensrecord.service.ts
- test/integration/migration/migration.spec.ts
- test/unit/controllers/locrequest.controller.shared.ts
- test/unit/controllers/records.controller.spec.ts
- test/unit/services/locsynchronization.service.spec.ts
* Logic is almost a copy/paste of what we already have for collection items
* Main differences are:
* Any contributor can add records (not only requester)
* The download of a record file is linked to an actual item (enabling ownership check)
* No ownership check at record level (it is irrelevant)
logion-network/logion-internal#773
> Add tokens record API and model

- resources/schemas.json
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/migration/1677148843394-LocTemplate.ts
- src/logion/model/locrequest.model.ts
- test/unit/model/locrequest.model.spec.ts
- yarn.lock
* Add template field to LOC requests.
* The field is unconstrained (but still limited to 255 characters) text as everything is handled frontend-side. One exception: the SOF template value is automatically injected by the LOC request factory.
* The purpose of not using an enumeration is to fully delegate the handling of LOC templates to the frontend. Indeed, the constraints linked to a LOC template will only be managed frontend-side which enables a higher flexibility.
* LOC templates are more a way to describe best practices rather than imposing some data invariant.
> LOC template

- resources/schemas.json
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
* Passing requester address in the body is actually required when a LOC is directly created by the LLO, which happens in 2 situations:
* Logion Identity LOC
* Creation of a new LOC to replace a to be voided one
logion-network/logion-internal#852
> Accept requester on LOC creation by owner

- resources/schemas.json
- src/logion/controllers/adapters/locrequestadapter.ts
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/migration/1681743107271-AddItemSubmitterType.ts
- src/logion/model/locrequest.model.ts
- src/logion/model/supportedaccountid.model.ts
- src/logion/services/idenfy/idenfy.service.ts
- src/logion/services/locauthorization.service.ts
- test/helpers/addresses.ts
- test/integration/model/loc_requests.sql
- test/integration/model/loc_requests_order.sql
- test/integration/model/locrequest.model.spec.ts
- test/unit/controllers/collection.controller.spec.ts
- test/unit/controllers/idenfy.controller.spec.ts
- test/unit/controllers/locrequest.controller.fetch.spec.ts
- test/unit/controllers/locrequest.controller.items.spec.ts
- test/unit/controllers/locrequest.controller.shared.ts
- test/unit/controllers/locrequest.controller.sof.spec.ts
- test/unit/controllers/records.controller.spec.ts
- test/unit/model/locrequest.model.spec.ts
- test/unit/services/idenfy/idenfy.service.spec.ts
* Add address type to LOC Request files et metadata submitters.
* Introduces `EmbeddableSupportedAccountId`, used in both `LocFile` and `LocMetadataItem`.
**Not covered by this PR, to do later on...**
* `EmbeddableSupportedAccountId` might probably be used also in `LocRequestAggregateRoot`and `SessionAggregateRoot` (in this latter case it must be moved to `logion-rest-api-core`.
* Do the same job for attribute `owner` of delivered files.
logion-network/logion-internal#851
> Add address type to Loc Request Files and Metadata submitter.

- src/logion/controllers/locrequest.controller.ts
- src/logion/model/locrequest.model.ts
* An empty void reason is enforced if the reason field was not provided in the request.
logion-network/logion-internal#903
> Ensure void reason is always set

- resources/schemas.json
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/model/locrequest.model.ts
- test/integration/model/loc_requests.sql
- test/integration/model/loc_requests_order.sql
- test/integration/model/locrequest.model.spec.ts
- test/unit/controllers/locrequest.controller.creation.spec.ts
- test/unit/controllers/locrequest.controller.fetch.spec.ts
- test/unit/controllers/locrequest.controller.lifecycle.spec.ts
- test/unit/controllers/locrequest.controller.sof.spec.ts
- test/unit/model/locrequest.model.spec.ts
* LOC is now opened by the requester, provided that s(he) has a Polkadot Address.
* This is therefore not applicable when the requester is an Logion Identity LOC, or an Ethereum address.
* The review status are aligned to Item's review status:
* A requested LOC is now `REVIEW_PENDING`  (previously: `REQUESTED`).
* If the LLO rejects, it becomes `REVIEW_REJECTED` (previously: `REJECTED`).
* If the LLO accepts for a Polkadot requester, it becomes `REVIEW_ACCEPTED` (previously: `OPEN`).
* If the LLO accepts for a non-Polkadot requester, it becomes `OPEN` (unchanged).
---
⚠️ This covers only the minimal yet functional requirements to start front development. Missing backend features (mainly data migration and synchronization) will come later on.
logion-network/logion-internal#908
> LOC opened by Polakdot requester

- package.json
- src/logion/migration/1686211213240-DropDraft.ts
- src/logion/migration/1686211513637-RenameLocStatus.ts
- yarn.lock
* Two migrations: one to drop deprecated columns and the other to migrate statuses
logion-network/logion-internal#910
> Add migration for new statuses

- src/logion/model/locrequest.model.ts
- test/unit/model/locrequest.model.spec.ts
* When a LOC is created by the LO (non-polkadot requester or logion ID), status must be OPEN, not REVIEW_PENDING.
> Sometimes wrong LOC request status on create

- package.json
- resources/schemas.json
- src/logion/controllers/adapters/locrequestadapter.ts
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/lib/crypto/hashing.ts
- src/logion/migration/1686924244354-AddMetadataNameHash.ts
- src/logion/model/locrequest.model.ts
- src/logion/services/locsynchronization.service.ts
- test/integration/model/loc_requests.sql
- test/integration/model/locrequest.model.spec.ts
- test/unit/controllers/locrequest.controller.fetch.spec.ts
- test/unit/controllers/locrequest.controller.items.spec.ts
- test/unit/lib/crypto/hashing.spec.ts
- test/unit/model/locrequest.model.spec.ts
- test/unit/services/locsynchronization.service.spec.ts
- yarn.lock
* A new attribute `nameHash` (the hash of the name...) is added as a key to access a Metadata Item.
* The `name` of an item is now nullable.
* A migration is added to calculate the hash for the existing items, and to setup the new Primary Key.
* During Metadata item creation, the hash is calculated, stored and returned in all subsequent queries.
* The REST api docs is completed.
___
The Postgres type `bytea` is used, allowing a more efficient storage than `varchar(255)`. A similar technique could be used for loc file hashes, and collection item ids.
logion-network/logion-internal#937
> Supports for deletable Metadata

- package.json
- resources/schemas.json
- src/logion/container/app.container.ts
- src/logion/controllers/components.ts
- src/logion/services/multiversx.service.ts
- src/logion/services/ownershipcheck.service.ts
- test/unit/services/ownershipcheck.service.spec.ts
- yarn.lock
* Add support for `Bech32` addresses.
* Enable ownership check for various MultiversX ESDT tokens (STF and NFT's)
logion-network/logion-internal#945
> Multiversx: add siganture verification

- resources/schemas.json
- src/logion/controllers/collection.controller.ts
- src/logion/controllers/components.ts
- src/logion/controllers/records.controller.ts
- src/logion/migration/1689170305381-AddItemPublicData.ts
- src/logion/migration/1689239362222-AddRecordPublicData.ts
- src/logion/model/collection.model.ts
- src/logion/model/tokensrecord.model.ts
- src/logion/services/collection.service.ts
- src/logion/services/file.storage.service.ts
- src/logion/services/locsynchronization.service.ts
- src/logion/services/tokensrecord.service.ts
- test/integration/migration/migration.spec.ts
- test/integration/model/collection.model.spec.ts
- test/integration/model/collection_items.sql
- test/unit/controllers/collection.controller.spec.ts
- test/unit/controllers/records.controller.spec.ts
- test/unit/model/collection.model.spec.ts
- test/unit/services/locsynchronization.service.spec.ts
* Story https://github.com/logion-network/logion-internal/issues/948 requires that all public data related to items and records are submitted to the backend, otherwise hashing them on-chain would lead to a data loss
* Public data are submitted to backend before extrinsic submission in order to prevent concurrent updates (sync and client) and the potential data loss this represents (sync does not have the public data anymore, while client does).
* If extrinsic submission fails, submitted public data must be discarded.
* As a result, file upload is simplified: the collection items and tokens records always exist in the DB on upload (but have no CID as long as the file has not been uploaded).
* The mechanism has been implemented for collection items and tokens records. …
> Store public item/record data

- resources/schemas.json
- src/logion/controllers/adapters/locrequestadapter.ts
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/migration/1693307866605-AcknowledgedByVerifiedIssuer.ts
- src/logion/model/locrequest.model.ts
- src/logion/services/locsynchronization.service.ts
- test/unit/controllers/locrequest.controller.fetch.spec.ts
- test/unit/model/locrequest.model.spec.ts
- test/unit/services/locsynchronization.service.spec.ts
- yarn.lock
* When a metadata or file was submitted by a Verified Issuer, it must be acknowledged by both the LOC owner and the Verified Issuer in order to be considered as fully acknowledged.
* When the item was submitted by either the owner or the requester, then only the LOC owner must acknowledge as before.
* `protobuf` was upgraded in order to fix a dependabot alert.
logion-network/logion-internal#969
> Support Verified Issuer acknowledgment

- package.json
- src/logion/controllers/locrequest.controller.ts
- src/logion/model/locrequest.model.ts
- test/unit/controllers/locrequest.controller.items.spec.ts
- yarn.lock
* Authorize confirm for requester, when submitter is verified issuer.
* Always authorize confirm-acknowledge for loc owner, even if submitter is verified issuer. In this case there is double acknowledgment.
* Inject latest `node-api`.
logion-network/logion-internal#975
> Adapt confirm/confirm-acknowledge authorization.

- src/logion/migration/1693571860507-AddAckByBooleans.ts
- src/logion/model/locrequest.model.ts
* Adds ack flags in order to update item status even if ack date is not yet known (set by sync).
logion-network/logion-internal#971
> Refresh ack status on confirm

- src/logion/services/transaction.extractor.ts
- test/resources/transfer/block-transferAll.json
- test/resources/vault/block-approveCall.json
- test/unit/services/transaction.extractor.spec.ts
For all operations `balances.transfer*()`, the amount is picked up from the event `pallet.Transfer` rather then from the call args. Reason for this is that arg `value` is not available for `transferAll()`.
It's not clear if such an event is sent when running in the context of a vault approval, a [technical debt](https://github.com/logion-network/logion-internal/issues/990) to address this.
logion-network/logion-internal#989
> fix: synchro of balances.transferAll.

- src/logion/controllers/locrequest.controller.ts
- src/logion/model/locrequest.model.ts
- test/helpers/Mock.ts
- test/unit/controllers/locrequest.controller.items.spec.ts
- test/unit/model/locrequest.model.spec.ts
- test/unit/services/locsynchronization.service.spec.ts
* The publication confirmation by the requester when the requester submitted the item was broken.
* Probably unnoticed because it is actually fixed by sync.
logion-network/logion-internal#984
> Broken requester publication

- resources/schemas.json
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/migration/1695136615896-AddLinkSubmitterAndLifecycle.ts
- src/logion/model/locrequest.model.ts
- src/logion/services/locsynchronization.service.ts
- test/integration/model/loc_requests.sql
- test/integration/model/locrequest.model.spec.ts
- test/unit/controllers/locrequest.controller.fetch.spec.ts
- test/unit/controllers/locrequest.controller.items.spec.ts
- test/unit/model/locrequest.model.spec.ts
- test/unit/services/locsynchronization.service.spec.ts
* Add lifecycle (review, status, acknowledge) to LOC Link
* Add submitter to LOC Link
* Migrate existing links.
___
Remarks:
* Controller yet to be tested against new endpoints (review-request, review, confirm-acknowledge) for links, metadata and files.
* Field `draft` is temporarily kept in DB as a safety net. Next `typeorm migration:generate` will consequently suggest to drop it.
logion-network/logion-internal#996
> Align LOC links (lifecycle, submitter) on metadata and files.

- resources/schemas.json
- src/logion/controllers/components.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/model/locrequest.model.ts
- src/logion/services/idenfy/idenfy.service.ts
- test/integration/model/locrequest.model.spec.ts
- test/unit/controllers/collection.controller.spec.ts
- test/unit/controllers/locrequest.controller.items.spec.ts
- test/unit/model/locrequest.model.spec.ts
- test/unit/services/idenfy/idenfy.service.spec.ts
* A REST resource is added for direct LOC opening - including **metadata** and **links** (but not files).
* The concept of `SubmissionType` (`MANUAL_BY_USER` | `MANUAL_BY_OWNER` | `DIRECT_BY_REQUESTER`) is introduced, to better capture the various ways of submitting loc (requests) and items.
* The REST resource for uploading **files** content is adapted: A new parameter is available, direct (boolean), to tell the file is directly published (i.e. submissionType is `DIRECT_BY_REQUESTER`)
logion-network/logion-internal#1000
> Add REST resources for direct LOC opening

- src/logion/controllers/locrequest.controller.ts
- src/logion/model/locrequest.model.ts
- src/logion/services/locsynchronization.service.ts
- test/unit/controllers/locrequest.controller.items.spec.ts
- test/unit/controllers/locrequest.controller.lifecycle.spec.ts
- test/unit/model/locrequest.model.spec.ts
- test/unit/services/locsynchronization.service.spec.ts
* Adds controller tests for acknowledgment.
* Rename methods to clarify their "pre-chain submission" nature.
logion-network/logion-internal#907
> Rename pub/ack methods/resources and add missing controller tests

- src/logion/controllers/locrequest.controller.ts
- src/logion/lib/db/collections.ts
- src/logion/lib/http.ts
- src/logion/model/locrequest.model.ts
- test/unit/model/locrequest.model.spec.ts
* Pre-close fails if all items are not published/acknowledged (depending on case) on-chain
* The check consists in testing if timestamps (set by sync) are defined
* With this, we at least prevent erroneous auto-ack close on chain in case of stale/erroneous data client-side or in backend DB
logion-network/logion-internal#1083
> Ensure all items ack/pub on-chain on close

- src/logion/model/locrequest.model.ts
- test/unit/model/locrequest.model.spec.ts
* An accepted item cannot be removed by submitter (requester or VI).
* The LLO may still remove the item.
logion-network/logion-internal#1076
> Prevent item removal when accepted

- src/logion/controllers/adapters/locrequestadapter.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/migration/1706107298453-LinkLocToIdentity.ts
- src/logion/model/locrequest.model.ts
- test/unit/controllers/locrequest.controller.shared.ts
- test/unit/model/locrequest.model.spec.ts
Persist the link between the requester of a Transaction/Collection LOC and his/her valid identity LOC.
* The field `requesterIdentityLoc` is re-used - was previously used for referencing Logion identity only.
* The identity LOC has to be valid (i.e. closed and non-voided) at the creation time.
* Previously the identity LOC was fetched using field `requesterAddress` (and `requesterAddressType`).
* Those 2 latter fields are still being populated, even if this introduces a denormalization.
* A migration will populate the fields for all Transaction/Collection Polkadot identity.
* The user identity being now based on this link, the identity of a requester of a LOC is now the one used at LOC creation time, even if the identity has been voided-and-replaced in between. …
> Link Transaction/Collection LOCs to requester Identity LOC.

- resources/schemas.json
- src/logion/controllers/components.ts
- src/logion/controllers/protectionrequest.controller.ts
- src/logion/migration/1706536716815-LinkProtectionToIdentity.ts
- src/logion/model/protectionrequest.model.ts
- test/integration/model/protection_requests.sql
- test/unit/controllers/protectionrequest.controller.spec.ts
- test/unit/model/protectionrequest.model.spec.ts
- test/unit/services/notification-test-data.ts
Previously, the identity LOC ID was submitted by LLO, when `accept`ing the protection request.
So instead of dropping `loc_id` and creating `requester_identity_loc`, we now rename `loc_id` into `requester_identity_loc`.
Naming remains consistent with Transaction/Collection.
Also, as a prerequisite to protection creation, `requester_identity_loc` has no reason to be present in Decision only, and to stay nullable.
Companion of https://github.com/logion-network/logion-backend-ts/pull/289
logion-network/logion-internal#1126
> Remove now useless loc_id from protection accept resource.

- src/logion/controllers/locrequest.controller.ts
- src/logion/controllers/protectionrequest.controller.ts
- src/logion/controllers/vaulttransferrequest.controller.ts
- src/logion/model/locrequest.model.ts
- test/unit/controllers/locrequest.controller.shared.ts
- test/unit/controllers/protectionrequest.controller.spec.ts
- test/unit/controllers/vaulttransferrequest.controller.spec.ts
* Given the identity of a user has already been verified on the creation of its IDLOC, it is redundant to validate the protection request as well.
* Therefore, a user with 2 IDLOCs with 2 different LLOs is now able to directly activate its protection on chain without the preliminary review by the LLOs.
* However, the review is still required when requesting a recovery.
* Some clean-up and refactoring will be needed in order to simplify and clarify the model.
logion-network/logion-internal#1123
> Only recovery requests needed

- resources/schemas.json
- src/logion/controllers/components.ts
- src/logion/controllers/workload.controller.ts
- src/logion/model/locrequest.model.ts
- src/logion/model/protectionrequest.model.ts
- src/logion/model/vaulttransferrequest.model.ts
- src/logion/services/workload.service.ts
- test/integration/model/locrequest.model.spec.ts
- test/integration/model/protectionrequest.model.spec.ts
- test/integration/model/vaulttransferrequest.model.spec.ts
- test/unit/controllers/workload.controller.spec.ts
- test/unit/services/workload.service.spec.ts
* Exposes the workload of a list of legal officers.
* Intended use is to have one call per backend, with all legal officers "hosted" on the backend given as parameter.
logion-network/logion-internal#1136
> Expose workloads of many legal officers.

- package.json
- src/logion/controllers/locrequest.controller.ts
- src/logion/controllers/records.controller.ts
- src/logion/services/locauthorization.service.ts
- test/unit/controllers/locrequest.controller.creation.spec.ts
- test/unit/controllers/locrequest.controller.items.spec.ts
- test/unit/controllers/locrequest.controller.lifecycle.spec.ts
- test/unit/controllers/locrequest.controller.shared.ts
- test/unit/controllers/records.controller.spec.ts
- test/unit/model/locrequest.model.spec.ts
- test/unit/services/sponsorship.service.spec.ts
- yarn.lock
When a LOC is requested by someone having a Polkadot address, the LLO, owner of the LOC, may not add or remove items (i.e. files, metadata or links). He cannot request reviews of those items either.
logion-network/logion-internal#1169
> Fix: items addition/deletion forbidden for owner

- src/logion/model/verifiedissuerselection.model.ts
- src/logion/services/locsynchronization.service.ts
- src/logion/services/verifiedissuerselection.service.ts
- test/integration/model/verifiedthirdpartyselection.model.spec.ts
* fix: ID loc retrieval on verified issuer dismissal sync;
* fix: `unselectAll` using wrong prefix.
logion-network/logion-internal#1247
> Fix issuer dismissal sync failure

- resources/mail/secret-recovery-requested-legal-officer.pug
- resources/mail/secret-recovery-requested-user.pug
- resources/schemas.json
- src/logion/app.support.ts
- src/logion/container/app.container.ts
- src/logion/controllers/components.ts
- src/logion/controllers/secret_recovery.controller.ts
- src/logion/migration/1715669632901-AddSecrets.ts
- src/logion/migration/1715933228153-AddSecretRecovery.ts
- src/logion/model/locrequest.model.ts
- src/logion/model/secret_recovery.model.ts
- src/logion/services/notification.service.ts
- src/logion/services/secret_recovery.service.ts
- test/integration/migration/migration.spec.ts
- test/unit/controllers/secret_recovery.controller.spec.ts
- test/unit/model/secret_recovery.model.spec.ts
* Provides a public (no authentication) to request a secret recovery.
* 2 Notification are sent:
* to the legal officer, as the usual notification of work.
* to the requester, to confirm his/her request.
logion-network/logion-internal#1255
> Secret Recovery Request

- resources/mail/recoverable-secret-added.pug
- resources/mail/secret-recovery-accepted.pug
- resources/mail/secret-recovery-rejected.pug
- resources/mail/secret-recovery-requested-user.pug
- resources/schemas.json
- src/logion/app.support.ts
- src/logion/container/app.container.ts
- src/logion/controllers/components.ts
- src/logion/controllers/protectionrequest.controller.ts
- src/logion/controllers/recovery.controller.ts
- src/logion/controllers/secret_recovery.controller.ts
- src/logion/migration/1716302125635-AddSecretStatus.ts
- src/logion/model/decision.ts
- src/logion/model/protectionrequest.model.ts
- src/logion/model/secret_recovery.model.ts
- src/logion/services/notification.service.ts
- src/logion/services/secret_recovery.service.ts
- test/unit/controllers/protectionrequest.controller.spec.ts
- test/unit/controllers/recovery.controller.spec.ts
- test/unit/controllers/secret_recovery.controller.spec.ts
- test/unit/controllers/vaulttransferrequest.controller.spec.ts
- test/unit/model/protectionrequest.model.spec.ts
- test/unit/model/secret_recovery.model.spec.ts
- test/unit/services/notification-test-data.ts
* Adds a resource to retrieve all recovery requests (account and secret) in a single HTTP request.
* Enriches model to enable acceptance/rejection of a secret recovery request.
* Standardizes recovery request review (same view for account and secret recovery).
logion-network/logion-internal#1263
> Enable secret recovery review and decision

- .env.sample
- resources/mail/README.md
- resources/mail/all-documented-vars.pug
- resources/mail/legal-officer-details.pug
- resources/schemas.json
- src/logion/app.support.ts
- src/logion/container/app.container.ts
- src/logion/controllers/account_recovery.controller.ts
- src/logion/controllers/components.ts
- src/logion/controllers/legalofficer.controller.ts
- src/logion/controllers/locrequest.controller.ts
- src/logion/controllers/secret_recovery.controller.ts
- src/logion/controllers/vaulttransferrequest.controller.ts
- src/logion/migration/1718188396630-AddLegalOfficers.ts
- src/logion/model/legalofficer.model.ts
- src/logion/services/accountrecoverysynchronization.service.ts
- src/logion/services/directory.service.ts
- src/logion/services/legalOfficerService.ts
- src/logion/services/locsynchronization.service.ts
- test/helpers/addresses.ts
- test/integration/migration/migration.spec.ts
- test/unit/controllers/account_recovery.controller.spec.ts
- test/unit/controllers/legalofficer.controller.spec.ts
- test/unit/controllers/locrequest.controller.shared.ts
- test/unit/controllers/secret_recovery.controller.spec.ts
- test/unit/controllers/vaulttransferrequest.controller.spec.ts
- test/unit/model/legalofficer.model.spec.ts
- test/unit/services/accountrecoverysynchronizer.service.spec.ts
- test/unit/services/locsynchronization.service.spec.ts
- test/unit/services/notification-test-data.ts
* Directory service is moved from [logion-directory](https://github.com/logion-network/logion-directory) to backend.
* Notifications cannot be sent to other legal officers - feature was anyway no more used.
* `DirectoryService` is renamed to `LegalOfficerService`.
NOTE: Migration does not include data - will be done manually later on.
logion-network/logion-internal#1292
> Decentralize directory
