README.md, doc/Authentication.md, doc/Authentication.puml, resources/schemas.json, src/logion/controllers/authentication.controller.ts, test/unit/controllers/authentication.controller.spec.ts
logion-network/logion-internal#164
Updated doc:
=> Authentication stubs

src/logion/model/protectionrequest.model.ts, test/integration/model/protectionrequest.model.spec.ts
logion-network/logion-internal#156
=> feat: fix regression.

resources/schemas.json, src/logion/app.ts, src/logion/controllers/locrequest.controller.ts, src/logion/controllers/tokenizationrequest.controller.ts, src/logion/model/locrequest.model.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#172
=> feat: loc model and fake api resources.

resources/schemas.json, src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/unit/controllers/locrequest.controller.spec.ts
logion-network/logion-internal#172
=> feat: implement fetch and create endpoints.

resources/schemas.json, src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts, test/unit/model/tokenizationrequest.model.spec.ts
logion-network/logion-internal#172
=> feat: implement accept and reject endpoints.

resources/schemas.json, src/logion/controllers/protectionrequest.controller.ts, src/logion/controllers/tokenizationrequest.controller.ts, src/logion/controllers/transaction.controller.ts, src/logion/model/tokenizationrequest.model.ts, test/unit/controllers/protectionrequest.controller.spec.ts, test/unit/controllers/tokenizationrequest.controller.spec.ts
logion-network/logion-internal#179
=> feat: remove signature validation; remove useless endpoint /protection-request/check; adapt doc to reflect authentication requirements.

resources/schemas.json, src/logion/controllers/locrequest.controller.ts, src/logion/controllers/protectionrequest.controller.ts, src/logion/controllers/tokenizationrequest.controller.ts, src/logion/model/tokenizationrequest.model.ts, test/integration/model/tokenization_requests.sql, test/integration/model/tokenizationrequest.model.spec.ts, test/unit/controllers/protectionrequest.controller.spec.ts, test/unit/controllers/tokenizationrequest.controller.spec.ts, test/unit/model/tokenizationrequest.model.spec.ts
logion-network/logion-internal#179
=> feat: remove signature, signedOn from all endpoints except authenticate; remove useless sessionToken.

resources/schemas.json, src/logion/controllers/locrequest.controller.ts, src/logion/model/addresses.model.ts, src/logion/model/locrequest.model.ts, src/logion/model/protectionrequest.model.ts, src/logion/model/useridentity.ts, src/logion/services/authentication.service.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#181
=> feat: add user identity to loc.

src/logion/model/locrequest.model.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.spec.ts
logion-network/logion-internal#181
=> feat: test user identity of locs.

resources/schemas.json, src/logion/container/app.container.ts, src/logion/controllers/locrequest.controller.ts, src/logion/lib/crypto/hashing.ts, src/logion/lib/db/large_objects.ts, src/logion/services/fileimport.service.ts, test/helpers/testapp.ts, test/integration/lib/db/file.txt, test/integration/lib/db/large_objects.spec.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/lib/crypto/file.txt, test/unit/lib/crypto/hashing.spec.ts
logion-network/logion-internal#190
=> feat: upload, hash and import file.

src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts
logion-network/logion-internal#198
=> feat: fix LOC files persistence and add pre-close.

resources/schemas.json, src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, src/logion/services/locsynchronization.service.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts, test/unit/services/locsynchronization.service.spec.ts
logion-network/logion-internal#227
=> feat: add links to LOC requests.

src/logion/services/polkadot.service.ts
logion-network/logion-internal#227
=> feat: align with latest node type definitions.

src/logion/services/blockconsumption.service.ts, src/logion/services/extrinsic.data.extractor.ts, src/logion/services/transaction.extractor.ts, test/resources/recovery/block-06-recovery-asRecovered.json, test/unit/services/transaction.extractor.spec.ts
logion-network/logion-internal#222
=> feat: synchronize transfers done in recovery.

src/logion/lib/uuid.ts, test/unit/lib/uuid.spec.ts
Closes logion-network/logion-internal#245
=> fix: decimalToUuid with hex having leading zero.

Dockerfile, README.md, doc/DbMigration.md, ormconfig.json.sample, package.json, src/logion/migration/1636720219315-InitialSchema.ts
logion-network/logion-internal#246
=> feat: configure TypeOrm migrations.

db-tools/LogionNamingStrategy.ts, db-tools/ormconfig.ts, ormconfig.json.sample, package.json, resources/schemas.json, src/logion/container/app.container.ts, src/logion/controllers/locrequest.controller.ts, src/logion/controllers/transaction.controller.ts, src/logion/migration/1637061269576-TransactionErrors.ts, src/logion/model/transaction.model.ts, src/logion/services/block.service.ts, src/logion/services/error.service.ts, src/logion/services/transaction.extractor.ts, src/logion/services/transaction.vo.ts, src/logion/services/transactionsync.service.ts, src/logion/services/types/responses/Extrinsic.ts, test/integration/model/transactions.sql, test/resources/transfer/block-transferKeepAliveFailed.json, test/unit/controllers/transaction.controller.spec.ts, test/unit/model/transaction.model.spec.ts, test/unit/services/transaction.extractor.spec.ts, tsconfig.app.json
logion-network/logion-internal#241
logion-network/logion-internal#246
=> Report error transactions / Fine-tune DB constraints naming.

src/logion/controllers/locrequest.controller.ts, src/logion/migration/1637229545243-AddLocFileUniqueConstraint.ts, src/logion/model/locrequest.model.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#251
=> fix: add missing contraint on LOC files.

src/logion/model/transaction.model.ts, test/integration/model/transaction.model.spec.ts
logion-network/logion-internal#241
=> feat: filter out failed transactions when queried as recipient.

src/logion/model/child.ts, src/logion/model/locrequest.model.ts, test/helpers/testdb.ts, test/integration/model/locrequest.model.spec.ts, test/integration/model/protectionrequest.model.spec.ts, test/integration/model/session.model.spec.ts, test/integration/model/sessions.sql, test/integration/model/syncpoint.model.spec.ts, test/integration/model/transaction.model.spec.ts
logion-network/logion-internal#261
=> DB transactions

src/logion/migration/1637834996469-MakeMetadataValueText.ts, src/logion/model/locrequest.model.ts, test/integration/model/loc_requests.sql
logion-network/logion-internal#269
=> feat: set metadata value text.

README.md, resources/schemas.json, src/logion/controllers/locrequest.controller.ts, src/logion/lib/db/large_objects.ts, src/logion/migration/1638269147841-AddVoidInfo.ts, src/logion/model/locrequest.model.ts, src/logion/services/locsynchronization.service.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#263
logion-network/logion-internal#264
=> feat: void loc.

src/logion/app.ts, src/logion/scheduler/scheduler.service.ts, src/logion/services/block.service.ts, src/logion/util/Log.ts
logion-network/logion-internal#271
=> feat: allow no-weight transactions.

src/logion/model/locrequest.model.ts, src/logion/model/protectionrequest.model.ts
logion-network/logion-internal#273
=> feat: make synchronization idem-potent.

src/logion/services/block.service.ts, src/logion/services/blockconsumption.service.ts, src/logion/services/locsynchronization.service.ts, src/logion/services/protectionsynchronization.service.ts, src/logion/services/transaction.extractor.ts, src/logion/services/types/responses/Extrinsic.ts, test/unit/services/blockconsumption.service.spec.ts, test/unit/services/locsynchronization.service.spec.ts, test/unit/services/protectionsynchronization.service.spec.ts
logion-network/logion-internal#274
=> Avoid syncing extrinsics with errors; add logging.

resources/schemas.json, src/logion/controllers/locrequest.controller.ts, src/logion/migration/1638955476613-AddAttributesForDraft.ts, src/logion/model/locrequest.model.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#280
=> feat: add nature to uploaded file.

resources/schemas.json, src/logion/controllers/locrequest.controller.ts, src/logion/lib/assertions.ts, src/logion/migration/1638955476613-AddAttributesForDraft.ts, src/logion/model/child.ts, src/logion/model/locrequest.model.ts, src/logion/services/locsynchronization.service.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts, test/unit/services/locsynchronization.service.spec.ts
logion-network/logion-internal#280
=> feat: add endpoints to add/confirm/delete links and metadata.

.env.sample, src/logion/app.ts, src/logion/container/app.container.ts, src/logion/controllers/doc.ts, src/logion/controllers/health.controller.ts, src/logion/services/authentication.service.ts, src/logion/services/locsynchronization.service.ts, test/unit/controllers/health.controller.spec.ts, test/unit/services/locsynchronization.service.spec.ts
logion-network/logion-internal#290
=> feat: add health resource.

src/logion/model/locrequest.model.ts, test/unit/model/locrequest.model.spec.ts
fix: sync stopped when timestamp already set.
logion-network/logion-internal#280
=> fix: items are not updated.

src/logion/model/locrequest.model.ts
logion-network/logion-internal#279
=> feat: sort loc requests by creation date.

resources/schemas.json, src/logion/controllers/locrequest.controller.ts, src/logion/migration/1639999832301-AddRequesterIdLoc.ts, src/logion/model/locrequest.model.ts, src/logion/services/polkadot.service.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#298
=> feat: add identity loc as requester.

src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#299
=> feat: fix LOC request relations.

resources/schemas.json, src/logion/controllers/locrequest.controller.ts, test/unit/controllers/locrequest.controller.spec.ts
logion-network/logion-internal#312
=> feat: API update for file/metadata submitter .

src/logion/controllers/locrequest.controller.ts, test/helpers/testapp.ts, test/unit/controllers/locrequest.controller.spec.ts
logion-network/logion-internal#316
=> fix: enforce that loc-related resources are called by node owner.

resources/schemas.json, src/logion/controllers/locrequest.controller.ts, src/logion/migration/1641978274519-AddItemSubmitter.ts, src/logion/model/locrequest.model.ts, src/logion/services/authentication.service.ts, src/logion/services/polkadot.service.ts, test/helpers/testapp.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#313
=> fix: implement submitter persistence.

src/logion/services/blockconsumption.service.ts, yarn.lock
=> fix: memory exhaustion upon long sync.

src/logion/lib/polkadot/interfaces/default/types.ts, src/logion/lib/polkadot/interfaces/definitions.ts
logion-network/logion-internal#337
=> fix: unblock sync.

src/logion/services/polkadot.service.ts, tsconfig.json
logion-network/logion-internal#337
=> feat: properly use Polkadot custom types.

src/logion/container/app.container.ts, src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/helpers/testapp.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#339
=> feat: add new LOC item delete rules.

.nycrc.json, resources/schemas.json, src/logion/model/locrequest.model.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#351
=> feat: add loc type "Collection"

src/logion/services/authentication.service.ts, test/unit/controllers/authentication.controller.spec.ts, test/unit/controllers/health.controller.spec.ts, test/unit/services/authentication.service.spec.ts
logion-network/logion-internal#364
=> feat: use chain to authenticate LO.

src/logion/model/locrequest.model.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#371
=> fix: fix LOC request status in sync.

resources/schemas.json, src/logion/container/app.container.ts, src/logion/controllers/authentication.controller.ts, src/logion/controllers/locrequest.controller.ts, src/logion/services/authentication.service.ts, src/logion/services/authority.service.ts, test/helpers/testapp.ts, test/unit/controllers/health.controller.spec.ts, test/unit/services/authentication.service.spec.ts, test/unit/services/authority.service.spec.ts
logion-network/logion-internal#370
* Implement `/auth/refresh`
* Remove useless JWT attribute `legalOfficer`.
* Add `AuthorityService`.
=> feat: refresh token.

.env.sample, resources/mail/README.md, resources/mail/all-documented-vars.txt, resources/mail/protection-accepted.txt, resources/mail/protection-rejected.txt, resources/mail/protection-requested.txt, resources/mail/recovery-rejected.txt, resources/mail/recovery-requested.txt, src/logion/controllers/protectionrequest.controller.ts, src/logion/model/legalofficer.model.ts, src/logion/services/directory.service.ts, src/logion/services/notification.service.ts, test/integration/services/mail.service.spec.ts, test/integration/services/notification.service.spec.ts, test/integration/services/test-helpers/envhelper.ts, test/resources/mail/protection-requested.txt, test/unit/controllers/protectionrequest.controller.spec.ts, test/unit/services/notification-test-data.ts, test/unit/services/notification.service.spec.ts
logion-network/logion-internal#378
=> feat: add legal officer info to notifications; add all templates.

resources/mail/loc-created.pug, src/logion/controllers/locrequest.controller.ts, src/logion/services/notification.service.ts, test/unit/controllers/locrequest.controller.spec.ts
logion-network/logion-internal#385
=> feat: notifies wallet user upon loc creation.

resources/mail/legal-officer-details.pug, resources/mail/loc-accepted.pug, resources/mail/loc-created.pug, resources/mail/loc-rejected.pug, resources/mail/protection-accepted.pug, resources/mail/protection-rejected.pug, resources/mail/recovery-accepted.pug, resources/mail/recovery-rejected.pug, test/unit/services/notification.service.spec.ts
logion-network/logion-internal#385
=> feat: factor out legal officer details in mail templates.

resources/mail/README.md, resources/mail/all-documented-vars.pug, resources/mail/vault-transfer-accepted.pug, resources/mail/vault-transfer-rejected.pug, resources/mail/vault-transfer-requested.pug, resources/schemas.json, src/logion/app.support.ts, src/logion/container/app.container.ts, src/logion/controllers/vaulttransferrequest.controller.ts, src/logion/migration/1646830695574-AddVaultTransfer.ts, src/logion/model/vaulttransferrequest.model.ts, src/logion/services/notification.service.ts, test/integration/migration/migration.spec.ts, test/integration/model/vault_transfer_requests.sql, test/integration/model/vaulttransferrequest.model.spec.ts, test/unit/controllers/vaulttransferrequest.controller.spec.ts, test/unit/model/vaulttransferrequest.model.spec.ts, test/unit/services/notification-test-data.ts
logion-network/logion-internal#393
=> feat: add vault transfer requests.

.env.sample, src/logion/controllers/locrequest.controller.ts, src/logion/controllers/protectionrequest.controller.ts, src/logion/model/protectionrequest.model.ts, src/logion/services/mail.service.ts, src/logion/services/notification.service.ts, test/integration/services/mail.service.spec.ts, test/unit/controllers/protectionrequest.controller.spec.ts, test/unit/services/notification-test-data.ts
* Fix decision
* Refactor notifications
* Allow STARTTLS.
=> Fix decision ; Refactor notifications ; Allow STARTTLS.

src/logion/controllers/transaction.controller.ts, test/unit/controllers/transaction.controller.spec.ts
logion-network/logion-internal#391
=> feat: disable authentication when fetching transactions.

resources/schemas.json, src/logion/controllers/vaulttransferrequest.controller.ts, src/logion/migration/1646830695574-AddVaultTransfer.ts, src/logion/model/vaulttransferrequest.model.ts, test/integration/model/vault_transfer_requests.sql, test/integration/model/vaulttransferrequest.model.spec.ts, test/unit/controllers/vaulttransferrequest.controller.spec.ts, test/unit/model/vaulttransferrequest.model.spec.ts, test/unit/services/notification-test-data.ts
logion-network/logion-internal#393
=> feat: remove vault transfer call.

resources/mail/vault-transfer-cancelled.pug, resources/schemas.json, src/logion/controllers/vaulttransferrequest.controller.ts, src/logion/model/vaulttransferrequest.model.ts, src/logion/services/notification.service.ts, test/unit/controllers/vaulttransferrequest.controller.spec.ts, test/unit/model/vaulttransferrequest.model.spec.ts
logion-network/logion-internal#393
=> feat: add cancelled status.

resources/schemas.json, src/logion/controllers/vaulttransferrequest.controller.ts
logion-network/logion-internal#400
=> feat: add missing fields in views.

.dockerignore, README.md, logion-postgres/Dockerfile, logion-postgres/pgcrypto.sh, package.json, resources/schemas.json, src/logion/controllers/transaction.controller.ts, src/logion/migration/1647428322698-ChangeTransactionPrimaryKey.ts, src/logion/model/transaction.model.ts, src/logion/services/polkadot.service.ts, src/logion/services/transaction.extractor.ts, src/logion/services/transactionsync.service.ts, test/resources/vault/block-approveCall.json, test/unit/controllers/transaction.controller.spec.ts, test/unit/model/transaction.model.spec.ts, test/unit/services/transaction.extractor.spec.ts
logion-network/logion-internal#400
=> feat: enable phantom transactions.

resources/schemas.json, src/logion/controllers/vaulttransferrequest.controller.ts, src/logion/model/vaulttransferrequest.model.ts, test/unit/controllers/vaulttransferrequest.controller.spec.ts, test/unit/model/vaulttransferrequest.model.spec.ts
logion-network/logion-internal#76
=> feat: enable cancel/resubmit post reject.

.env.sample, src/logion/lib/crypto/EncryptedFile.ts, src/logion/services/file.storage.service.ts, test/unit/lib/crypto/EncryptedFile.spec.ts
logion-network/logion-internal#436
=> feat: encrypt/decrypt file when storing to/retrieving from IPFS .

resources/mail/sof-requested.pug, resources/schemas.json, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, src/logion/services/notification.service.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#447
=> feat: creates a SOF request.

src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#447
logion-network/logion-internal#444
=> chore: adapt link nature for SOF on Collection Item.

src/logion/model/child.ts, test/unit/model/child.spec.ts
logion-network/logion-internal#463
=> fix: failure to reindex LOC child items after deletion.

src/logion/app.support.ts, src/logion/controllers/fileupload.ts, src/logion/controllers/locrequest.controller.ts, src/logion/controllers/lofile.controller.ts, src/logion/migration/1652954519291-AddLoFile.ts, src/logion/model/lofile.model.ts, src/logion/services/file.storage.service.ts, test/integration/migration/migration.spec.ts, test/integration/model/lo_files.sql, test/integration/model/lofile.model.spec.ts, test/unit/controllers/lofile.controller.spec.ts, test/unit/model/lofile.model.spec.ts
logion-network/logion-internal#476
=> feat: allow LO to upload/download files.

src/logion/lib/db/collections.ts, src/logion/model/child.ts, src/logion/model/locrequest.model.ts, test/unit/model/child.spec.ts
logion-network/logion-internal#463
=> fix: order indexed children before update.

resources/schemas.json, src/logion/controllers/components.ts, src/logion/controllers/protectionrequest.controller.ts
logion-network/logion-internal#489
=> fix: no 500 in case of missing protection.

src/logion/controllers/protectionrequest.controller.ts, test/unit/controllers/protectionrequest.controller.spec.ts
logion-network/logion-internal#500
=> feat: save protection request upon update, cancel or resubmit.

src/logion/services/error.service.ts
logion-network/logion-internal#520
=> fix: transaction error.

package.json, resources/schemas.json, src/logion/container/app.container.ts, src/logion/controllers/collection.controller.ts, src/logion/controllers/components.ts, src/logion/migration/1657037110989-AddCollectionItemFile.ts, src/logion/model/collection.model.ts, src/logion/services/collection.service.ts, test/helpers/filehelper.ts, test/integration/migration/migration.spec.ts, test/integration/model/collection.model.spec.ts, test/integration/model/collection_items.sql, test/unit/controllers/collection.controller.spec.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/collection.model.spec.ts, test/unit/services/locsynchronization.service.spec.ts, yarn.lock
logion-network/logion-internal#515
=> feat: upload/download file to/from collection item.

src/logion/controllers/collection.controller.ts, test/unit/controllers/collection.controller.spec.ts
logion-network/logion-internal#515
=> feat: check uploaded file name against published item file.

src/logion/controllers/collection.controller.ts, src/logion/controllers/errors.ts, test/unit/controllers/collection.controller.spec.ts
* feat: return published collection item even if not yet in DB.
* feat: 400 bad request error returns same payload as 500.
* 
logion-network/logion-internal#515
=> feat: return published collection item even if not yet in DB.

package.json, resources/schemas.json, src/logion/container/app.container.ts, src/logion/controllers/authentication.controller.ts, src/logion/controllers/components.ts, src/logion/services/signature.service.ts, test/unit/controllers/authentication.controller.spec.ts, test/unit/ethereum.spec.ts, test/unit/services/signature.service.spec.ts, yarn.lock
logion-network/logion-internal#535
=> feat: allow to authenticate an Ethereum address.

src/logion/services/Etherscan.service.ts, src/logion/services/etherscanscrapper.ts, src/logion/services/ownershipcheck.service.ts, test/unit/services/etherscanscrapper.spec.ts, test/unit/services/ownershipcheck.service.spec.ts
logion-network/logion-internal#541
=> feat: simplify ownership check.

src/logion/controllers/collection.controller.ts, test/unit/controllers/collection.controller.spec.ts
logion-network/logion-internal#547
=> feat: add check download resource.

resources/schemas.json, src/logion/controllers/collection.controller.ts, src/logion/controllers/components.ts, test/unit/controllers/collection.controller.spec.ts
logion-network/logion-internal#562
=> Check ownership of deliveries

package.json, src/logion/controllers/locrequest.controller.ts, src/logion/lib/CsvCreator.ts, test/unit/controllers/locrequest.controller.spec.ts, yarn.lock
logion-network/logion-internal#567
=> feat: add CSV generation for Transaction LOCs.

resources/schemas.json, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, src/logion/migration/1662373797382-AddPostalAddressToLocRequest.ts, src/logion/model/legalofficer.model.ts, src/logion/model/locrequest.model.ts, src/logion/model/postaladdress.ts, src/logion/model/protectionrequest.model.ts, test/unit/model/locrequest.model.spec.ts, test/unit/services/notification-test-data.ts
logion-network/logion-internal#573
=> feat: add user postal address to Identity LOC request.

resources/schemas.json, src/logion/container/app.container.ts, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, src/logion/lib/crypto/hashing.ts, src/logion/migration/1663083586613-AddSealSalt.ts, src/logion/model/locrequest.model.ts, src/logion/services/seal.service.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts, test/unit/services/seal.service.spec.ts
logion-network/logion-internal#581
=> feat: seal identity LOC on close.

resources/schemas.json, src/logion/container/app.container.ts, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, src/logion/migration/1663232819326-AddSealHash.ts, src/logion/model/locrequest.model.ts, src/logion/model/personalinfo.model.ts, src/logion/services/locsynchronization.service.ts, src/logion/services/seal.service.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts, test/unit/services/seal.service.spec.ts
* Compute and expose seal upon identity LOC request creation.
* Include all personal data in seal.
* Enable to update timestamp when closing and sealing.
=> Improve Seal

resources/schemas.json, src/logion/controllers/collection.controller.ts, src/logion/controllers/components.ts, src/logion/model/collection.model.ts, test/integration/model/collection.model.spec.ts, test/integration/model/collection_items.sql, test/unit/controllers/collection.controller.spec.ts
* Add new REST resource and query
logion-network/logion-internal#615
=> Add resource to fetch all collection items

resources/schemas.json, src/logion/controllers/collection.controller.ts, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, test/unit/controllers/locrequest.controller.spec.ts
logion-network/logion-internal#607
=> Expose identity LOC ID

src/logion/controllers/locrequest.controller.ts, test/unit/controllers/locrequest.controller.spec.ts
* Enforces identity constraints: A valid Identity LOC must exist on each transaction request.
* Enforces one identity LOC per LO per Polkadot account.
logion-network/logion-internal#626
=> Enforces identity constraints.

resources/schemas.json, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
* Added DRAFT status
* Enable LOC editing (files, links and metadata items) when DRAFT or OPEN
* DRAFT LOCs may be submitted (they then become REQUESTED) or canceled (they are deleted, as well as submitted files)
logion-network/logion-internal#634
=> Enable draft mode

src/logion/services/blockconsumption.service.ts
logion-network/logion-internal#638
=> Add logging on sync error

src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/unit/controllers/locrequest.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#634
=> Expose draft items to submitter

src/logion/controllers/fileupload.ts
logion-network/logion-internal#641
=> fix: returns an error when uploaded file is truncated.

Dockerfile, package.json, src/logion/app.ts, src/logion/container/app.container.ts, src/logion/services/blockconsumption.service.ts, src/logion/services/prometheus.service.ts, test/unit/services/blockconsumption.service.spec.ts, yarn.lock
* Prometheus metrics are now exposed by the backend
* Node.js default metrics are configured
* Last block synchronized gauge is provided
logion-network/logion-internal#654
=> Expose prometheus metrics

src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/unit/controllers/locrequest.controller.creation.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#670
=> Remove direct OPEN loc creation.

src/logion/model/locrequest.model.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#678
=> vtp flag set in request description.

resources/schemas.json, src/logion/controllers/adapters/locrequestadapter.ts, src/logion/controllers/adapters/verifiedthirdpartyadapter.ts, src/logion/controllers/components.ts, src/logion/controllers/verifiedthirdparty.controller.ts, src/logion/model/verifiedthirdpartyselection.model.ts, test/integration/model/verifiedthirdpartyselection.model.spec.ts, test/unit/controllers/locrequest.controller.shared.ts, test/unit/controllers/verifiedthirdparty.controller.spec.ts
* Just added a resource
* Filtering-out of items was already implemented for regular users and the rule is actually the same for VTPs
=> Add resource for VTP LOCs

src/logion/controllers/adapters/verifiedthirdpartyadapter.ts, src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.creation.spec.ts, test/unit/controllers/locrequest.controller.fetch.spec.ts, test/unit/controllers/locrequest.controller.items.spec.ts, test/unit/controllers/locrequest.controller.lifecycle.spec.ts, test/unit/controllers/locrequest.controller.shared.ts, test/unit/controllers/locrequest.controller.sof.spec.ts
* Ensure authenticated user is a valid contributor (owner, requester or selected VTP) on fetch, add, delete and download.
=> Enable VTP contribution

resources/schemas.json, src/logion/controllers/adapters/verifiedthirdpartyadapter.ts, src/logion/controllers/components.ts
=> Add address to verified third party.

src/logion/container/app.container.ts, src/logion/controllers/collection.controller.ts, src/logion/model/child.ts, src/logion/model/collection.model.ts, src/logion/services/collection.service.ts, src/logion/services/locsynchronization.service.ts, test/integration/model/collection.model.spec.ts, test/unit/controllers/collection.controller.spec.ts, test/unit/services/locsynchronization.service.spec.ts
* Refactors collection item repository
* Adds transaction boundaries on collection item updates
logion-network/logion-internal#644
=> Use transaction for collection items

src/logion/controllers/locrequest.controller.ts, test/unit/controllers/locrequest.controller.sof.spec.ts
* Allow VTP to request a SOF on the LOC where is selected.
* Remove user identity duplicate to SOF.
=> Allow selected vtp to request a SOF.

src/logion/model/locrequest.model.ts, test/unit/model/locrequest.model.spec.ts
=> Allow requester to see owner-submitted draft files and metadata.

src/logion/controllers/verifiedthirdparty.controller.ts, src/logion/model/verifiedthirdpartyselection.model.ts, test/integration/model/verifiedthirdpartyselection.model.spec.ts, test/integration/model/vtp_selection.sql, test/unit/controllers/verifiedthirdparty.controller.spec.ts
* Previously selected LOCs are now excluded
=> Fix list of VTP LOCs

src/logion/app.support.ts, src/logion/controllers/lofile.controller.ts, src/logion/controllers/setting.controller.ts
* Changes settings and LO files API for guest LLOs.
logion-network/logion-internal#702
=> Change settings and LO files API for guest LLOs

src/logion/controllers/lofile.controller.ts, src/logion/controllers/setting.controller.ts, yarn.lock
* Check that authenticated user is LO on node (and not only node owner).
logion-network/logion-internal#702
=> Fix permissions on settings and LO files

src/logion/controllers/locrequest.controller.ts, src/logion/services/directory.service.ts, src/logion/services/protectionsynchronization.service.ts, test/unit/services/protectionsynchronization.service.spec.ts
* SOF request has now the same owner as source LOC.
* Protection Synchronizer now synchronizes protections of many LLO's.
logion-network/logion-internal#701
=> Adapt processes to many LLO's on same backend.

src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts
logion-network/logion-internal#701
=> Adapt Polkadot identity LOC check to multiple LLO's.

Dockerfile, README.md, docker/base/Dockerfile, package.json, tsconfig.json, yarn.lock
* Upgrade dependencies
* Upgrade to Node 18
=> Upgrade dependencies

src/logion/controllers/adapters/locrequestadapter.ts
logion-network/logion-internal#701
=> Ensure valid identity LOC detection is done with correct LLO.

package.json, test/unit/controllers/locrequest.controller.items.spec.ts, test/unit/controllers/locrequest.controller.lifecycle.spec.ts, test/unit/controllers/locrequest.controller.shared.ts, test/unit/controllers/protectionrequest.controller.spec.ts, test/unit/controllers/vaulttransferrequest.controller.spec.ts, yarn.lock
logion-network/logion-internal#701
=> Check access of other LLO's on same backend 

resources/schemas.json, src/logion/app.support.ts, src/logion/controllers/components.ts, src/logion/controllers/vote.controller.ts
* Define the API for LO to fetch votes (s)he must perform.
logion-network/logion-internal#717
=> Define vote fetching api.

resources/schemas.json, src/logion/controllers/adapters/locrequestadapter.ts, src/logion/controllers/components.ts, src/logion/model/locrequest.model.ts, src/logion/services/idenfy/idenfy.service.ts, test/unit/controllers/locrequest.controller.shared.ts, test/unit/model/locrequest.model.spec.ts
* Adds iDenfy data to LOC request view
* Prevents submission of draft LOC if iDenfy session in progress
logion-network/logion-internal#710
=> feat: add iDenfy data to LOC request view.

resources/schemas.json, src/logion/container/app.container.ts, src/logion/controllers/adapters/locrequestadapter.ts, src/logion/controllers/components.ts, src/logion/controllers/vote.controller.ts, src/logion/migration/1671620889950-AddVote.ts, src/logion/model/vote.model.ts, test/integration/migration/migration.spec.ts, test/integration/model/vote.model.spec.ts, test/integration/model/votes.sql, test/unit/controllers/locrequest.controller.fetch.spec.ts, test/unit/controllers/locrequest.controller.shared.ts, test/unit/controllers/vote.controller.spec.ts
* Add database table.
* Read votes from database.
* Expose vote ID in LOC view, if applicable.
=> Implement Vote resources

src/logion/controllers/locrequest.controller.ts
* LLOs are allowed to view LOC and download attached files when a vote exists on the LOC.
logion-network/logion-internal#717
=> Allow voters to view LOC.

test/unit/controllers/locrequest.controller.fetch.spec.ts, test/unit/controllers/locrequest.controller.items.spec.ts, test/unit/controllers/locrequest.controller.shared.ts
logion-network/logion-internal#717
=> Test voter access to LOC.

README.md, doc/DbMigration.md, resources/schemas.json, src/logion/controllers/components.ts, src/logion/controllers/vote.controller.ts, src/logion/migration/1673968386608-AddBallot.ts, src/logion/model/vote.model.ts, test/integration/migration/migration.spec.ts, test/integration/model/vote.model.spec.ts, test/integration/model/votes.sql, test/unit/controllers/vote.controller.spec.ts, test/unit/model/vote.spec.ts, yarn.lock
* Include vote ballots in model and view
* No sync yet
* Upgrade of some dependencies in order to fix security alerts
logion-network/logion-internal#729
=> Vote ballots

src/logion/lib/crypto/EncryptedFile.ts, src/logion/model/vote.model.ts, src/logion/services/vote.service.ts, src/logion/services/votesynchronization.service.ts
* Encryption speed is improved by increasing buffer size (was ridiculously small)
* Creates ballots following votes
* Closes vote and sets result
logion-network/logion-internal#729
=> Sync votes and optimize encryption

src/logion/migration/1674568650993-AddLocFileDelivered.ts, src/logion/model/locrequest.model.ts, test/integration/migration/migration.spec.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.lifecycle.spec.ts, test/unit/model/locrequest.model.spec.ts
* Adds LOC file delivery entity.
logion-network/logion-internal#742
=> Add LOC file deliveries

src/logion/controllers/collection.controller.ts, src/logion/model/locrequest.model.ts, test/unit/controllers/collection.controller.spec.ts, test/unit/model/locrequest.model.spec.ts
* Refactor and fix restricted delivery of Collection files.
* Test endpoints.
logion-network/logion-internal#740
=> Refactor and test restricted delivery of collection files.

src/logion/controllers/collection.controller.ts, src/logion/model/locrequest.model.ts, test/unit/model/locrequest.model.spec.ts
* Handles a TypeORM "bug" (see comment in model).
logion-network/logion-internal#741
=> Fix LOC file update

package.json, src/logion/controllers/collection.controller.ts, src/logion/services/collection.service.ts, src/logion/services/ownershipcheck.service.ts, test/unit/controllers/locrequest.controller.sof.spec.ts, test/unit/services/ownershipcheck.service.spec.ts, yarn.lock
* Fixes imports following upgrade.
logion-network/logion-internal#751
=> Upgrade node-api

resources/schemas.json, src/logion/controllers/collection.controller.ts, src/logion/controllers/components.ts, src/logion/model/locrequest.model.ts, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/collection.controller.spec.ts
* Add a public resource to check one single collection file delivery.
* Correct and improve endpoints documentation.
logion-network/logion-internal#750
logion-network/logion-internal#738
=> Add resource to check one single collection file delivery.

src/logion/controllers/collection.controller.ts, test/unit/controllers/collection.controller.spec.ts
logion-network/logion-internal#775
=> Remove useless check resources.

resources/schemas.json, src/logion/controllers/components.ts, src/logion/controllers/verifiedthirdparty.controller.ts, test/unit/controllers/verifiedthirdparty.controller.spec.ts, yarn.lock
* Gives access to the identity of all issuers of authenticated LO
logion-network/logion-internal#772
=> Add missing resource

.env.sample, package.json, src/logion/services/alchemy.service.ts, src/logion/services/ownershipcheck.service.ts, yarn.lock
* Check ownership of NFT on Polygon Mainnet and Mumbai.
* Each network requires its own Alchemy key.
logion-network/logion-internal#778
=> Add Polygon token ownership check.

src/logion/controllers/collection.controller.ts, src/logion/controllers/records.controller.ts, src/logion/services/ownershipcheck.service.ts, test/unit/controllers/collection.controller.spec.ts, test/unit/controllers/records.controller.spec.ts, test/unit/services/ownershipcheck.service.spec.ts
* Ownership check now explicitly requires token to be defined.
* Restricted delivery flag does not impact ownership check anymore (but does prevent the download of files under restricted delivery if not set).
logion-network/logion-internal#791
=> Link ownership to token only

src/logion/services/alchemy.service.ts, src/logion/services/ownershipcheck.service.ts, test/unit/services/alchemy.service.spec.ts, test/unit/services/ownershipcheck.service.spec.ts
* Refactor Alchemy service.
* Add support for ERC20 tokens.
logion-network/logion-internal#789
=> feat: enable ERC20 ownership check.

src/logion/model/locrequest.model.ts
* Handled at model level.
* There is still a risk of collision, but with a lower probability of happening.
logion-network/logion-internal#792
=> Skip pre-close if already closed

src/logion/services/locauthorization.service.ts
logion-network/logion-internal#851
=> Enable Ethereum address to contribute to requested LOC.

resources/schemas.json, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, src/logion/migration/1682056857552-AddSponsorshipId.ts, src/logion/model/locrequest.model.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/model/locrequest.model.spec.ts, yarn.lock
* Adds sponsorship ID to LOC request in model and API.
* Upgardes TypeORM (solves dependabot alert).
logion-network/logion-internal#861
=> Add sponsorship ID

package.json, resources/schemas.json, src/logion/container/app.container.ts, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, src/logion/migration/1682336662176-AddSponsorshipIdUK.ts, src/logion/model/locrequest.model.ts, src/logion/services/sponsorship.service.ts, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.creation.spec.ts, test/unit/controllers/locrequest.controller.shared.ts, test/unit/services/sponsorship.service.spec.ts, yarn.lock
* Ensure that provided Sponsorship ID is valid at LOC creation time.
* Note: It's technically not possible to verify upfront if a given Sponsorship ID is referenced more than once in draft/requested LOC's with distinct backend's.
logion-network/logion-internal#875
=> Ensure sponsorship id validity.

src/logion/controllers/locrequest.controller.ts, src/logion/services/sponsorship.service.ts, test/helpers/addresses.ts, test/unit/controllers/locrequest.controller.creation.spec.ts, test/unit/controllers/locrequest.controller.shared.ts, test/unit/services/sponsorship.service.spec.ts
logion-network/logion-internal#875
=> Validate sponsorship against legal officer and requester.

.env.sample, package.json, resources/schemas.json, src/logion/container/app.container.ts, src/logion/controllers/components.ts, src/logion/controllers/config.controller.ts, src/logion/controllers/idenfy.controller.ts, src/logion/services/idenfy/idenfy.service.ts, test/helpers/asynchelper.ts, test/unit/controllers/config.controller.spec.ts, test/unit/controllers/idenfy.controller.spec.ts, test/unit/services/idenfy/idenfy.service.spec.ts, test/unit/services/sponsorship.service.spec.ts, yarn.lock
* Add resume URL to verification session creation.
* Remove useless secret.
logion-network/logion-internal#884
=> iDenfy: make backend multi-front compatible

package.json, src/logion/controllers/records.controller.ts, src/logion/services/extrinsic.data.extractor.ts, src/logion/services/extrinsicsbuilder.ts, src/logion/services/protectionsynchronization.service.ts, src/logion/services/transaction.extractor.ts, src/logion/services/types/responses/Extrinsic.ts, src/logion/services/votesynchronization.service.ts, test/unit/controllers/records.controller.spec.ts, test/unit/services/locsynchronization.service.spec.ts, yarn.lock
* Consequence of https://github.com/logion-network/logion-internal/issues/842
* Some parts of the code were still using deprecated API elements
=> Fix following deprecated removal

package.json, resources/schemas.json, src/logion/controllers/adapters/locrequestadapter.ts, src/logion/controllers/components.ts, src/logion/controllers/transaction.controller.ts, src/logion/migration/1685091855598-AddTransactionType.ts, src/logion/model/transaction.model.ts, src/logion/services/extrinsicsbuilder.ts, src/logion/services/locsynchronization.service.ts, src/logion/services/transaction.extractor.ts, src/logion/services/transaction.vo.ts, src/logion/services/types/responses/Extrinsic.ts, test/integration/model/transaction.model.spec.ts, test/integration/model/transactions.sql, test/resources/loc/block-create-loc.json, test/unit/controllers/transaction.controller.spec.ts, test/unit/model/transaction.model.spec.ts, test/unit/services/locsynchronization.service.spec.ts, test/unit/services/transaction.extractor.spec.ts, yarn.lock
* Syncs legal fees as a value transfer
* Adds type to transactions
* Confirms metadata/file acknowledgement (sets timestamp)
* Still missing: set fees at LOC request level
logion-network/logion-internal#894
logion-network/logion-internal#899
=> Sync legal fees and confirm acknowledgment

src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/unit/controllers/locrequest.controller.items.spec.ts
* When an item is confirmed by the LOC owner, it should actually be acknowledged.
=> Some confirmations aknownledge as well

src/logion/controllers/locrequest.controller.ts, src/logion/migration/1686234465150-DropDraft.ts, src/logion/model/locrequest.model.ts, src/logion/services/locrequest.service.ts, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.lifecycle.spec.ts, test/unit/model/locrequest.model.spec.ts
* Companion of https://github.com/logion-network/logion-api/pull/158
logion-network/logion-internal#911
=> Enable rework/cancel on reviewed requests

package.json, resources/schemas.json, src/logion/controllers/adapters/locrequestadapter.ts, src/logion/controllers/components.ts, src/logion/migration/1687351664609-AddLegalCertificateFees.ts, src/logion/model/fees.ts, src/logion/model/locrequest.model.ts, src/logion/model/transaction.model.ts, src/logion/services/extrinsicsbuilder.ts, src/logion/services/locsynchronization.service.ts, src/logion/services/ownershipcheck.service.ts, src/logion/services/transaction.extractor.ts, src/logion/services/transaction.vo.ts, src/logion/services/types/responses/Extrinsic.ts, test/unit/controllers/collection.controller.spec.ts, test/unit/controllers/locrequest.controller.fetch.spec.ts, test/unit/controllers/records.controller.spec.ts, test/unit/controllers/transaction.controller.spec.ts, test/unit/model/transaction.model.spec.ts, test/unit/services/ownershipcheck.service.spec.ts, yarn.lock
* Legal and certificate fees are added to transactions.
* Certificate fees are exposed.
* DB is migrated.
* Synchronization is adapted.
___
* node-api is upgraded and `Fees` and `ItemToken` used accordingly.
___
logion-network/logion-internal#932
logion-network/logion-internal#939
=> Add legal and certificate fees to transactions

package.json, resources/schemas.json, src/logion/controllers/adapters/locrequestadapter.ts, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, src/logion/migration/1691656359969-AddLegalFees.ts, src/logion/model/fees.ts, src/logion/model/locrequest.model.ts, src/logion/model/transaction.model.ts, src/logion/services/extrinsicsbuilder.ts, src/logion/services/transaction.extractor.ts, src/logion/services/types/responses/Extrinsic.ts, src/logion/services/votesynchronization.service.ts, test/unit/controllers/locrequest.controller.creation.spec.ts, test/unit/controllers/locrequest.controller.shared.ts, test/unit/model/locrequest.model.spec.ts, yarn.lock
* Companion of https://github.com/logion-network/logion-api/pull/176
* Initial support for reserved balance in transactions (used by value fees)
logion-network/logion-internal#959
=> Add value fees

src/logion/model/locrequest.model.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#974
=> Fix LOC items status and listing

doc/DbMigration.md, resources/schemas.json, src/logion/controllers/adapters/locrequestadapter.ts, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, src/logion/migration/1694509475979-AddLegalFee.ts, src/logion/model/locrequest.model.ts, test/integration/model/loc_requests.sql, test/integration/model/loc_requests_order.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.creation.spec.ts, test/unit/controllers/locrequest.controller.fetch.spec.ts, test/unit/controllers/locrequest.controller.shared.ts, test/unit/controllers/locrequest.controller.sof.spec.ts, test/unit/model/locrequest.model.spec.ts, test/unit/services/notification-test-data.ts
* Adds field to LOC request.
* No attempt to rebuild an history. Not impossible but rather difficult and probably mostly useless. Open to discuss.
logion-network/logion-internal#982
=> Add legal fee to LOC request

src/logion/controllers/adapters/locrequestadapter.ts, src/logion/controllers/locrequest.controller.ts, test/unit/controllers/locrequest.controller.fetch.spec.ts
* Expose submitter and lifecycle attributes of links.
* Adapt authorization of delete link.
* Fix URL of links request, review, confirm-ack.
=> Adapt link submission

src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/unit/model/locrequest.model.spec.ts
* Enable review of items when LOC is pending.
* Add missing notifications when reviewing items on an open LOC.
logion-network/logion-internal#1025
=> Enable item review with pending LOC

src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, src/logion/services/locrequest.service.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#1041
=> Add roll-back resources

src/logion/model/locrequest.model.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#1072
=> Only accept LOC with all items accepted

src/logion/model/locrequest.model.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#1076
=> Align remove conditions with UI

src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/unit/controllers/locrequest.controller.lifecycle.spec.ts, test/unit/model/locrequest.model.spec.ts
logion-network/logion-internal#1040
logion-network/logion-internal#1084
=> Add cancel pre-void

resources/schemas.json, src/logion/app.support.ts, src/logion/container/app.container.ts, src/logion/controllers/components.ts, src/logion/controllers/workload.controller.ts, src/logion/services/workload.service.ts, test/unit/controllers/workload.controller.spec.ts, test/unit/services/workload.service.spec.ts
* Takes into account pending LOC/vault transfer/recovery requests.
logion-network/logion-internal#1136
=> Expose workload of legal officer

resources/schemas.json, src/logion/controllers/adapters/locrequestadapter.ts, src/logion/controllers/collection.controller.ts, src/logion/controllers/components.ts, src/logion/controllers/locrequest.controller.ts, src/logion/migration/1710862720387-AddCollectionParams.ts, src/logion/model/collection.model.ts, src/logion/model/locrequest.model.ts, test/integration/model/collection.model.spec.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.fetch.spec.ts, test/unit/model/locrequest.model.spec.ts
* Store and expose collection-specific parameters: `lastBlockSubmission`, `maxSize`, `canUpload`.
logion-network/logion-internal#1179
=> Add collection params to model.

src/logion/controllers/records.controller.ts, src/logion/services/locauthorization.service.ts
* Enables LOC owner to contribute tokens records.
* Checks that tokens records submission is properly authorized (i.e. user is owner, requester or invited contributor).
logion-network/logion-internal#1185
=> fix: tokens records submission authorization.

package.json, src/logion/controllers/transaction.controller.ts, src/logion/migration/1711093251628-AddBlockNumber.ts, src/logion/model/block.model.ts, src/logion/model/syncpoint.model.ts, src/logion/model/transaction.model.ts, src/logion/services/block.service.ts, src/logion/services/blockconsumption.service.ts, src/logion/services/prometheus.service.ts, src/logion/services/syncpoint.service.ts, src/logion/services/transaction.extractor.ts, src/logion/services/transaction.vo.ts, src/logion/services/transactionsync.service.ts, src/logion/services/types/responses/Block.ts, test/integration/model/syncpoint.model.spec.ts, test/integration/model/syncpoints.sql, test/integration/model/transaction.model.spec.ts, test/integration/model/transactions.sql, test/unit/controllers/transaction.controller.spec.ts, test/unit/model/syncpoint.model.spec.ts, test/unit/model/transaction.model.spec.ts, test/unit/services/blockconsumption.service.spec.ts, test/unit/services/transactionsync.service.spec.ts, yarn.lock
* Stores chain type in transactions and sync points.
* Enables sync switch from solo to para.
* Exposes only transactions of connected chain.
logion-network/logion-internal#1183
=> Enable sync chain switch

package.json, src/logion/controllers/collection.controller.ts, src/logion/controllers/records.controller.ts, src/logion/services/ownership/alchemy.service.ts, src/logion/services/ownership/astar.service.ts, src/logion/services/ownership/multiversx.service.ts, src/logion/services/ownership/singular.service.ts, src/logion/services/ownershipcheck.service.ts, test/unit/services/ownership/alchemy.service.spec.ts, test/unit/services/ownership/astar.service.spec.ts, test/unit/services/ownershipcheck.service.spec.ts, yarn.lock
Uses https://github.com/logion-network/logion-api/pull/252
logion-network/logion-internal#1216
=> Use ValidAccountId for ownership check.

package.json, src/logion/controllers/locrequest.controller.ts, src/logion/model/locrequest.model.ts, test/integration/model/loc_requests.sql, test/integration/model/locrequest.model.spec.ts, test/unit/controllers/locrequest.controller.shared.ts, yarn.lock
* Any non-void IDLOC linking a requester to an owner should prevent the creation of a new IDLOC with the same owner and requester.
* Upgrades `@astar-network/*` dependencies.
logion-network/logion-internal#1239
logion-network/logion-internal#1192
=> Prevent creation of redundant IDLOC

package.json, src/logion/services/ownership/alchemy.service.ts, test/unit/services/ownership/alchemy.service.spec.ts, yarn.lock
* Uses Goerli and Mumbai keys to interact with Sepolia and Amoy.
logion-network/logion-internal#1244
=> Handle Sepolia and Amoy

package.json, src/logion/services/ownershipcheck.service.ts, test/unit/services/ownershipcheck.service.spec.ts
logion-network/logion-internal#1245
=> Fix ownership check

resources/schemas.json, src/logion/controllers/components.ts, src/logion/controllers/secret_recovery.controller.ts, src/logion/migration/1716820387622-SecretDownload.ts, src/logion/model/secret_recovery.model.ts, test/unit/controllers/recovery.controller.spec.ts, test/unit/controllers/secret_recovery.controller.spec.ts, test/unit/model/secret_recovery.model.spec.ts, test/unit/services/notification-test-data.ts
* Adds resource to download secret value through approved secret recovery request.
logion-network/logion-internal#1275
=> Enable secret download

package.json, yarn.lock
Upgrade logion/node-api.
logion-network/logion-internal#1283
=> Update logion/node-api for Polkadot-v1.10.0

package.json, yarn.lock
logion-network/logion-internal#1298
=> Update rest-api-core (human-readable message signature message).
